name: "zimg"
description: "A lightweight and high performance image storage and processing system."
baseurl: /

#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 15
